name: Build Marp slides
on:
  push:
    paths:
      - 'slides/**.md'
      - '.github/workflows/build-slides.yml'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Convert Markdown into HTML and PDF
      uses: KoharaKazuya/marp-cli-action@v4
      with:
        args: >-
          --input-dir slides
          --output dist
          --allow-local-files
        generate-html: true
        generate-pdf:  true

    - uses: actions/upload-artifact@v4
      with:
        name: Slides
        path: dist/
